---
title: ""
author: ""
date: "`r format(Sys.time(), '%B %d, %Y %H:%M')`"
output:
  html_document:
    number_sections: FALSE
    self_contained: TRUE
    code_folding: hide
    css: !expr here::here("www", "web_report.css")
    editor_options:
      chunk_output_type: console
---

<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>

<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato" />



```{r rmarkdown-setup, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r setup, cache = TRUE}
options(scipen = 999)


```

```{r}
library(tidyverse)
library(gt)

data <- tribble(
  ~`City or MSA`, ~`Home price`, ~`Fair market rent ($ millions)`, ~`Rent`, ~`First month principal`, ~`Rent vouchers`, ~`Homeownership vouchers`,
  "Houston, TX", 589, 589, 589, 589, 589, 589,
  "Philadelphia, PA", 296, 296, 296, 296, 296, 296,
  "Columbus, OH", 883, 883, 883, 883, 883, 883,
  "El Paso, TX", 296, 296, 296, 296, 296, 296,
  "Louisville, KY", 883, 883, 883, 883, 883, 883
)




random_id = random_id(n=10)

data %>% 
  gt(id = random_id) %>% 
  tab_options(table.width = px(760),
              table.align = "left", 
              heading.align = "left",
              # TODO: Discuss with Comms  whether border should extend across 
              # whole row at bottom or just across data cells
              # TODO: Discuss whether we want a source/notes field at bottom of tables
              table.border.top.style = "hidden",
              table.border.bottom.style = "hidden",
              heading.border.bottom.style = "hidden",
              # Need to set this to transparent so that cells_borders of the cells can display properly and 
              table_body.border.bottom.style = "transparent",
              table_body.border.top.style = "transparent",
              # column_labels.border.bottom.style = "transparent",
              column_labels.border.bottom.width = px(3),
              column_labels.border.bottom.color = "red",
              # row_group.border.top.style = "hidden",
              heading.title.font.size = px(14),
              heading.subtitle.font.size = px(18),
              column_labels.font.size = px(14),
              table.font.size = px(14),
              source_notes.font.size = px(12),
              ) %>% 
  tab_source_note(source_note = "Source: Narayanan, and Williams, 2019") %>% 
  tab_header(
    title = "eyebrow",
    subtitle = "Top 10 Banks (by Dollar Volume) for Community Development Lending") %>% 
  # Bold title, subtitle, and columns
  tab_style(
    style = cell_text(color = "black", weight = "bold", align = "left"),
    locations = cells_title("subtitle")
  ) %>% 
  tab_style(
    style = cell_text(color = "#696969", weight = "normal", align = "left", transform = "uppercase"),
    locations = cells_title("title")
  ) %>% 
  tab_style(
    style = cell_text(color = "black", weight = "bold", size = px(14)),
    locations = cells_column_labels(gt::everything())
  ) %>% 
  opt_table_font(
      font = list(
        google_font("Lato"),
        default_fonts()
      )
    ) %>% 
  # Adjust cell borders for all cells
  tab_style(
    style = list(
      cell_borders(
        sides = c("bottom"),
        color = "#d2d2d2",
        weight = px(1)
      )
    ),
    locations = list(
      cells_body(
        columns =  gt::everything()
        # rows = gt::everything()
      )
    )
  )  %>%
  # Set css for all the things we can't finetune exactly in gt, mostly padding
  opt_css(
    css = str_glue("
    #{random_id} .gt_row {{
      padding: 15px 15px 15px 15px;
    }}
    #{random_id} .gt_sourcenote {{
      padding: 16px 0px 16px 0px;
    }}
    #{random_id} .gt_subtitle {{
      padding: 0px 0px 32px 0px;
    }}
    #{random_id} .gt_col_heading {{
      padding: 0px 15px 10px 15px;
    }}
    ") %>% as.character()
  )

  
  
  
```


```{r reprex_for_github_issue, eval = FALSE}

library(tidyverse)
library(gt)
cars %>% 
  slice(1:5) %>% 
  gt() %>% 
  tab_options(
    # column_labels.border.bottom.style = "none",
    column_labels.border.bottom.color = "red",
    # column_labels.border.bottom.width = px(3),
    column_labels.border.top.color = "blue",
    # table_body.border.top.style = "none",
    table.border.top.color = "transparent",
    table.border.top.width = px(300),

    # table_body.border.top.color ="yellow",
    # table_body.border.top.width = px(1.6),
  ) 


```

